------------------------------------ Keymap ------------------------------------
local tl = require("telescope")
local tlb = require("telescope.builtin")
local helpers = require("helpers.misc")
local map = helpers.map

map("n","<leader>sb", tlb.buffers, "[S]earch [B]uffers")
map("n","<leader>sc", tlb.commands, "[S]earch [C]ommands")
map("n","<leader>sC", function () vim.notify("TODO: implement cheatsheat", vim.log.levels.WARN) end, "[S]earch [C]eatsheat")
map("n","<leader>sd", tlb.diagnostics, "[S]earch [D]iagnostics")
map("n","<leader>sf", tlb.find_files, "[S]earch [F]iles")
map("n","<leader>sgb",tlb.git_branches, "[G]it [B]ranch")
map("n","<leader>sgc",tlb.git_commits, "[G]it [C]ommits")
map("n","<leader>sgt",tlb.git_bcommits, "[G]it Buffer Commi[t]s")
map("n","<leader>sgf",tlb.git_files, "[G]it [F]iles")
map("n","<leader>sgs",tlb.git_status, "[G]it [S]tatus")
map("n","<leader>sga",tlb.git_stash, "[G]it St[a]sh")
map("n","<leader>sh", tlb.help_tags,"[S]earch [H]elp Tags")
map("n","<leader>sk", tlb.keymaps, "[S]earch [K]eys")
map("n","<leader>sM", tlb.man_pages, "[S]earch [M]an Pages")
map("n","<leader>sm", tlb.marks,"[S]earch [M]arks")
map("n","<leader>sn", function () tlb.find_files {cwd = vim.fn.stdpath('config')} end, "[S]earch [N]eovim Files")
map("n","<leader>so", tlb.oldfiles, "[S]earch [O]ldfiles")
map("n","<leader>sq", tlb.quickfix, "[S]earch [Q]uickFix List")
map("n","<leader>sQ", tlb.quickfixhistory, "[S]earch [Q]uickFix List History")
map("n","<leader>s.", tlb.resume, "[S]earch [O]ld")
map("n","<leader>sR", tlb.registers, "[S]earch [R]egisters")
map("n","<leader>ss", tlb.live_grep, "[S]earch with grep")
map("n","<leader>sS", tlb.symbols, "[S]earch [S]ymbols")
map("n","<leader>st", function () vim.notify("TODO: implement todo search", vim.log.levels.WARN) end,"[S]earch [T]odo")
map("n","<leader>sT", tlb.treesitter,"[S]earch [T]reesitter")
-- TODO: In buffer fuzzy search
--------------------------------------------------------------------------------
